create database EduSys
go
USE EduSys
GO

CREATE TABLE CHUYENDE (
	MACD NCHAR(5) NOT NULL PRIMARY KEY,
	TENCD NVARCHAR(50) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	HINH NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(225) NOT NULL
)
INSERT INTO CHUYENDE(MACD,TENCD,HOCPHI,THOILUONG,HINH,MOTA) VALUES(?,?,?,?)
UPDATE CHUYENDE SET TENCD = ?, HOCPHI = ?, THOILUONG = ?, HINH = ?, MOTA = ? WHERE MACD = ?
DELETE FROM CHUYENDE WHERE MACD = 'bb'
SELECT * FROM CHUYENDE
SELECT * FROM CHUYENDE WHERE MACD = ?

CREATE TABLE NHANVIEN (
	MANV NVARCHAR(20) NOT NULL PRIMARY KEY,
	MATKHAU NVARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	VAITRO BIT DEFAULT 0
)

INSERT INTO NHANVIEN(MANV,MATKHAU,HOTEN,VAITRO) VALUES(?,?,?,?)
INSERT INTO NHANVIEN(MANV,MATKHAU,HOTEN,VAITRO) VALUES('nv','11','nhân viên', 0)
INSERT INTO NHANVIEN(MANV,MATKHAU,HOTEN,VAITRO) VALUES('tp','11','nhân viên', 1)
UPDATE NHANVIEN SET MATKHAU = ?, HOTEN = ?, VAITRO = ? WHERE MANV = ?
DELETE FROM NHANVIEN WHERE MANV = ?
SELECT * FROM NHANVIEN
SELECT * FROM NHANVIEN WHERE MANV = ?

CREATE TABLE KHOAHOC (
	MAKH INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MACD NCHAR(5) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	NGAYKG DATE NOT NULL,
	GHICHU NVARCHAR(225) NULL,
	MANV NVARCHAR(20) NOT NULL,
	NGAYTAO DATE DEFAULT GETDATE()
	FOREIGN KEY (MACD) REFERENCES CHUYENDE(MACD) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
)
SELECT DISTINCT YEAR(NGAYKG) YEARS FROM KHOAHOC ORDER BY  YEAR(NGAYKG) DESC
INSERT INTO KHOAHOC(MAKH,MACD,HOCPHI,THOILUONG,NGAYKG,GHICHU,MANV) VALUES(?,?,?,?,?,?,?)
UPDATE KHOAHOC SET NGAYKG = ?,GHICHU = ? WHERE MAKH = ?
DELETE FROM KHOAHOC WHERE MAKH = ?
SELECT * FROM KHOAHOC
SELECT * FROM KHOAHOC WHERE MAKH = ?
SELECT TENCD FROM CHUYENDE
SELECT * FROM KHOAHOC WHERE MACD = 'bb'
INSERT INTO KHOAHOC(MACD,HOCPHI,THOILUONG,NGAYKG,GHICHU,MANV) VALUES('bb',53,43,'2/3/2000','ghi chu','nv')
INSERT INTO KHOAHOC(MACD,HOCPHI,THOILUONG,NGAYKG,GHICHU,MANV) VALUES('45',435,564,'2/3/2000','ghi chu','nv')
UPDATE KHOAHOC SET NGAYKG = '3/3/2021',GHICHU = 'shafh fhdsaf hsadkjf ' WHERE MAKH = 2

CREATE TABLE NGUOIHOC (
	MANH NCHAR(7) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH BIT DEFAULT 1,
	NGAYSINH DATE NOT NULL,
	DIENTHOAI NVARCHAR(24) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(225) NULL,
	MANV NVARCHAR(20) NOT NULL,
	NGAYDK DATE DEFAULT GETDATE(),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
)
INSERT INTO NGUOIHOC (MANH,HOTEN,GIOITINH,NGAYSINH,DIENTHOAI,EMAIL,GHICHU,MANV)  VALUES ('sdfdsa','FD',NULL,'12/23/1999','0123456789','DSAHF',NULL,'NV')
INSERT INTO NGUOIHOC(MANH,HOTEN,GIOITINH,NGAYSINH,DIENTHOAI,EMAIL,GHICHU,MANV,NGAYDK) VALUES(?,?,?,?,?,?,?,?,?,?)
UPDATE NGUOIHOC SET HOTEN = ?,GIOITINH = ?,NGAYSINH = ?,DIENTHOAI = ?,EMAIL = ?,GHICHU = ?,MANV = ?,NGAYDK = ? WHERE MANH = ?
DELETE FROM HOCVIEN WHERE MANH IN (SELECT MANH FROM NGUOIHOC WHERE MANH like 'PS02037')
DELETE FROM NGUOIHOC WHERE MANH = 'PS02037'
SELECT * FROM NGUOIHOC
SELECT * FROM NGUOIHOC WHERE MANH = ?
SELECT * FROM NGUOIHOC WHERE HOTEN LIKE '%n%'
SELECT * FROM HOCVIEN WHERE  MANH = 'PS03618'

CREATE TABLE HOCVIEN(
	MAHV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MAKH INT NOT NULL,
	MANH NCHAR(7) NOT NULL,
	DIEM FLOAT DEFAULT -1,
	FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH)  ON DELETE CASCADE ,
	FOREIGN KEY (MANH) REFERENCES NGUOIHOC(MANH) ON DELETE NO ACTION ON UPDATE CASCADE,
)

INSERT INTO HOCVIEN (MAHV,MAKH,MANH,DIEM)  VALUES (?,?,?,?)
UPDATE HOCVIEN SET DIEM = 10 WHERE MAHV = 5
DELETE FROM HOCVIEN WHERE MANH = ?
SELECT * FROM HOCVIEN WHERE MAKH = ?
SELECT * FROM KHOAHOC JOIN 
HOCVIEN ON HOCVIEN.MAKH =KHOAHOC.MAKH JOIN 
NGUOIHOC ON NGUOIHOC.MANH = NGUOIHOC.MANH

SELECT * FROM NGUOIHOC 
WHERE HOTEN LIKE '%?%' AND
MANH NOT IN  (SELECT MANH FROM HOCVIEN WHERE MAKH = ?)

CREATE PROC BANGDIEM (@MAKH INT)
AS BEGIN
	SELECT	
		NH.MANH,
		NH.HOTEN,
		ROUND(HV.DIEM,2) DIEM
		FROM HOCVIEN HV JOIN NGUOIHOC NH ON HV.MANH = NH.MANH
		WHERE HV.MAKH = @MAKH
		ORDER BY HV.DIEM DESC
	END
EXEC BANGDIEM 7
DROP PROC BANGDIEM

CREATE PROC DIEMCHUYENDE 
AS BEGIN 
	SELECT 
		TENCD CHUYENDE,
		ROUND(COUNT(MAHV),2) SOHV,
		ROUND(MIN(DIEM),2) THAPNHAT,
		ROUND(MAX(DIEM),2) CAONHAT,
		ROUND(AVG(DIEM),2)  TRUNGBINH
	FROM KHOAHOC KH JOIN HOCVIEN HV ON KH.MAKH = HV.MAKH
	JOIN CHUYENDE CD ON CD.MACD = KH.MACD
	GROUP BY TENCD
	END
EXEC DIEMCHUYENDE
DROP PROC DIEMCHUYENDE

CREATE PROC LUONGNGUOIHOC
AS BEGIN 
	SELECT
		YEAR(NGAYDK) NAM,
		COUNT(MANH) SONH,
		MIN(NGAYDK) SOMNHAT,
		MAX(NGAYDK) MUONNHAT
	FROM NGUOIHOC
	GROUP BY YEAR(NGAYDK)
	END
EXEC LUONGNGUOIHOC 
DROP PROC LUONGNGUOIHOC
CREATE PROC DOANHTHU (@YEAR INT)
AS BEGIN 
	SELECT	
		TENCD CHUYENDE,
		COUNT(DISTINCT KH.MAKH) SOKH,
		COUNT (HV.MAHV) SOHV,
		SUM(KH.HOCPHI) DOANHTHU,
		MIN(KH.HOCPHI) THATNHAT,
		MAX(KH.HOCPHI) CAONHAT,
		AVG(KH.HOCPHI) TRUNGBINH
	FROM CHUYENDE CD JOIN KHOAHOC KH ON KH.MACD = CD.MACD 
		JOIN HOCVIEN HV ON HV.MAKH = KH.MAKH
	WHERE YEAR(NGAYKG) = @YEAR
	GROUP BY TENCD
END
EXEC DOANHTHU 2007
DROP PROC DOANHTHU
SELECT * FROM NGUOIHOC
SELECT * FROM KHOAHOC where MACD = 'jav03'
SELECT * FROM HOCVIEN
SELECT * FROM CHUYENDE
SELECT * FROM NHANVIEN
SELECT * FROM NGUOIHOC	
delete from NGUOIHOC where	MANH = 'PS02988'
SET IDENTITY_INSERT [dbo].[KhoaHoc] OFF
INSERT [dbo].[NhanVien] ([MaNV], [MatKhau], [HoTen], [VaiTro]) VALUES (N'dt', N'11', N'Đào Ngọc Hoan', 1)
DROP TABLE HOCVIEN
drop table NGUOIHOC
DROP TABLE KHOAHOC
DROP TABLE CHUYENDE
DROP TABLE NHANVIEN

